# Everforest, minimal, aligned with i3.

enable_audio_bell no
visual_bell_duration 0.0

font_family      family="CaskaydiaCove Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12.0

window_padding_width 4
confirm_os_window_close 0
background_opacity 1.0

cursor_shape block
cursor_blink_interval 0
cursor_trail 3
cursor_trail_decay 0.1 0.4

tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template "{title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}"
active_tab_font_style bold
inactive_tab_font_style normal

foreground              #d3c6aa
background              #2d353b
selection_foreground    #2d353b
selection_background    #a7c080

cursor                  #7fbbb3
cursor_text_color       #2d353b

url_color               #83c092
active_border_color     #7fbbb3
inactive_border_color   #3d484d
bell_border_color       #dbbc7f

active_tab_foreground   #2d353b
active_tab_background   #7fbbb3
inactive_tab_foreground #859289
inactive_tab_background #343f44
tab_bar_background      #2d353b

color0  #3d484d
color1  #e67e80
color2  #a7c080
color3  #dbbc7f
color4  #7fbbb3
color5  #d699b6
color6  #83c092
color7  #d3c6aa
color8  #5c6a72
color9  #e67e80
color10 #a7c080
color11 #dbbc7f
color12 #7fbbb3
color13 #d699b6
color14 #83c092
color15 #d3c6aa
