[Metadata]
Name=Everforest
Version=1
Author=Codex
Description=Everforest dark theme
ScaleWithDPI=True

[InputPanel]
NormalColor=#d3c6aa
HighlightCandidateColor=#2d353b
HighlightColor=#d3c6aa
HighlightBackgroundColor=#a7c080
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=6
Right=6
Top=6
Bottom=6

[InputPanel/ContentMargin]
Left=3
Right=3
Top=3
Bottom=3

[InputPanel/Background]
Color=#2d353b
BorderColor=#7fbbb3
BorderWidth=2

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#a7c080

[InputPanel/Highlight/Margin]
Left=6
Right=6
Top=4
Bottom=4

[InputPanel/PrevPage]
Image=prev.png

[InputPanel/PrevPage/ClickMargin]
Left=6
Right=6
Top=4
Bottom=4

[InputPanel/NextPage]
Image=next.png

[InputPanel/NextPage/ClickMargin]
Left=6
Right=6
Top=4
Bottom=4

[Menu]
NormalColor=#d3c6aa
HighlightCandidateColor=#2d353b

[Menu/Background]
Color=#2d353b
BorderColor=#7fbbb3
BorderWidth=2

[Menu/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/ContentMargin]
Left=3
Right=3
Top=3
Bottom=3

[Menu/CheckBox]
Image=radio.png

[Menu/SubMenu]
Image=arrow.png

[Menu/Highlight]
Color=#a7c080

[Menu/Highlight/Margin]
Left=6
Right=6
Top=4
Bottom=4

[Menu/Separator]
Color=#5c6a72

[Menu/TextMargin]
Left=6
Right=6
Top=6
Bottom=6

[AccentColorField]
0=Input Panel Border
1=Input Panel Highlight Candidate Background
2=Input Panel Highlight
3=Menu Border
4=Menu Separator
5=Menu Selected Item Background
