[Appearance]
color_scheme_path=
custom_palette=true
icon_theme=Adwaita
standard_dialogs=default
style=kvantum

[Fonts]
fixed="CaskaydiaCove Nerd Font Mono,10,-1,5,50,0,0,0,0,0"
general="Sans,10,-1,5,50,0,0,0,0,0"

[Icon Theme]
fallback_theme=Adwaita

[Interface]
activate_item_on_single_click=1
buttonbox_layout=0
cursor_flash_time=1000
dialog_buttons_have_icons=1
double_click_interval=400
gui_effects=@Invalid()
keyboard_scheme=2
menus_have_icons=true
show_shortcuts_in_context_menus=true
stylesheets=@Invalid()
toolbutton_style=4
underline_shortcut=1
wheel_scroll_lines=3

[Palette]
active_base_color=#2d353b
active_button_color=#343f44
active_button_text_color=#d3c6aa
active_highlight_color=#7fbbb3
active_highlighted_text_color=#2d353b
active_link_color=#83c092
active_text_color=#d3c6aa
active_tooltip_base_color=#2d353b
active_tooltip_text_color=#d3c6aa
active_window_color=#343f44
active_window_text_color=#d3c6aa
disabled_base_color=#2d353b
disabled_button_color=#343f44
disabled_button_text_color=#859289
disabled_highlight_color=#5c6a72
disabled_highlighted_text_color=#2d353b
disabled_link_color=#5c6a72
disabled_text_color=#859289
disabled_window_color=#343f44
disabled_window_text_color=#859289
inactive_base_color=#2d353b
inactive_button_color=#343f44
inactive_button_text_color=#d3c6aa
inactive_highlight_color=#5c6a72
inactive_highlighted_text_color=#2d353b
inactive_link_color=#83c092
inactive_text_color=#d3c6aa
inactive_window_color=#343f44
inactive_window_text_color=#d3c6aa

